#11 `학습컨텐츠 등록` 저장소 구현
f-lab-edu/hello-study-world pull request #14
Opened 2022-10-23 14:02 UTC by abcshc

#11 

### Context and motivation
- `학습 컨텐츠`를 제공하기 위해 저장 기능을 구현하였습니다.

---

### Key implements
- `학습 컨텐츠`를 저장할 때 필요한 정보만 받기 위해 별도의 모델(`CreateContentModel`)을 만들었습니다.
- `학습 컨텐츠` 에서 조회에 사용할 사용자 정보를 `UserProfile`로 미리 분리했습니다.
- MediumTest를 위해 `사용자`의 정보를 미리 입력하는 Data SQL을 추가하였습니다.

2022-10-25 10:50 UTC, FrancescoJo commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/content/Content.kt
> +                deleted = false,
이 값은 test 등에서도 활용할 수 있으니, `deleted = false` 라는 기본 정책을 `create` 메소드의 파라미터로 구현해주세요.

```kotlin
fun create(
    id: UUID,
    url: String,
    description: String,
    providerUserProfile: UserProfile,
    registeredAt: Instant,
    lastUpdateAt: Instant,
    deleted: Boolean = false
): Content {
    return ContentModel.create(
...
        deleted = deleted,
...
    )
```

2022-10-25 10:51 UTC, FrancescoJo commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/content/Content.kt
> +                deleted = false,
`id`, `registeredAt`, `lastUpdatedAt` 등도 최초 생성시에 기본값 정책을 적용할 수 있을 것 같습니다.

2022-10-25 10:52 UTC, FrancescoJo commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/content/aggregate/ContentModel.kt
>      companion object {
만드는 방법이 이미 `CreateContent` 에 있기 때문에 여기는 굳이 `create` 같은 별도 메소드 안 빼도 괜찮습니다.

2022-10-25 10:53 UTC, FrancescoJo commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/content/aggregate/CreateContentModel.kt
> +    companion object {
여기도 같은 이유입니다. 만드는 방법이 이미 CreateContent 에 있기 때문에 굳이 create 같은 별도 메소드 안 빼도 괜찮습니다.

2022-10-25 10:54 UTC, FrancescoJo commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/content/CreateContent.kt
> +interface CreateContent {
`ContentRepository#createContent` 에 전달할 메시지네요. 그렇다면 이름을 `CreateContentMessage` 로 짓는게 어떨까 싶네요.

2022-10-25 10:55 UTC, FrancescoJo commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/user/UserProfile.kt
> +interface UserProfile {
이름의 의도를 보면 이용자의 기본 프로파일을 정의한 것 같은데, `UserBasicProfile`, `BasicUserProfile`, `SimpleUserProfile` 같은 구체적인 이름이 좀 더 좋겠습니다.

2022-10-25 10:56 UTC, FrancescoJo commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/user/aggregate/UserProfileModel.kt
> +    companion object {
불필요한 생성 메소드: `UserProfile#create` 를 이용하도록 유도해주세요.

2022-10-25 10:57 UTC, FrancescoJo commented on app-core/src/test/kotlin/test/domain/content/aggregate/ContentAggregateTestUtils.kt
> +fun randomCreateContent(
참고로 이런 식의 extension function 정의도 가능합니다.

```kotlin
fun CreateContent.Companion.random() { ... }
```

2022-10-25 10:58 UTC, FrancescoJo commented on app-core/src/test/kotlin/testcase/small/domain/content/CreateContentUseCaseSpec.kt
> +        `when`(contentRepository.create(any())).thenAnswer {
이런 식으로, SmallTest 에서 '저장' 기능을 수행하는 Repository 의 mock 은 어떻게 처리하는게 좋을까요?

2022-10-25 10:58 UTC, FrancescoJo commented on app-core/src/test/kotlin/testcase/small/domain/content/CreateContentUseCaseSpec.kt
> +            val now = Instant.now()
이런 규칙은 비즈니스 규칙에 가까워 보이는데, 여기 구현한 의도가 있을까요?

Test 가 실제 로직이 아니라 mock 의 로직에 의존하게 될텐데, 문제는 없을까요?

2022-10-25 10:59 UTC, FrancescoJo commented on app-infrastructure/src/main/kotlin/com/flab/hsw/core/jdbc/content/ContentEntity.kt
> +        else -> this.seq == other.seq
`seq` 는 무슨 값인가요? 비즈니스 규칙에서 정한 `ContentEntity` 의 식별자는 `uuid` 인가요, `seq` 인가요?

2022-10-25 11:00 UTC, FrancescoJo commented on app-infrastructure/src/main/kotlin/com/flab/hsw/core/jdbc/content/repository/ContentRepositoryImpl.kt
> +@Service
여기의 `@Service` 는 무슨 `@Service` 인가요? 혼란스럽지는 않나요?

```kotlin
@Service
annotation class RdbmsService
```

같은 식의 Annotation 확장도 괜찮습니다.

2022-10-25 11:02 UTC, FrancescoJo commented on app-infrastructure/src/main/kotlin/com/flab/hsw/core/jdbc/content/repository/ContentRepositoryImpl.kt
> +        return contentEntityDao.insert(ContentEntity.from(createContent, provider.seq!!))
19 라인에서 `provider` 를 `UUID` 타입인 `providerUserId` 로 찾았는데, `seq` 가 절대로 NULL 이 아니라는 보장이 있을까요?

2022-10-25 11:02 UTC, FrancescoJo commented on app-infrastructure/src/main/kotlin/com/flab/hsw/core/jdbc/content/repository/ContentRepositoryImpl.kt
> +        return contentEntityDao.insert(ContentEntity.from(createContent, provider.seq!!))
`seq` 필드가 흔히 쓰는 `id` 가 아닌 `seq` 라는 이름을 가진 이우가 뭘까요?

2022-10-25 11:04 UTC, FrancescoJo commented on app-infrastructure/src/main/kotlin/com/flab/hsw/core/jdbc/content/repository/ContentRepositoryImpl.kt
> +    private fun ContentEntity.toContent(providerUserEntity: UserEntity): Content {
이 로직은 `ContentEntity` 내에 있는게 좀 더 좋아보입니다. 객체 생성 책임을 `Repository` 가 지되,

만드는 방법은 자기 자신이 제공하는 식으로 로직을 응집시킵시다.

2022-10-25 11:04 UTC, FrancescoJo commented on app-infrastructure/src/main/kotlin/com/flab/hsw/core/jdbc/content/repository/ContentRepositoryImpl.kt
> +    private fun ContentEntity.toContent(providerUserEntity: UserEntity): Content {
왜냐면 우리 프로젝트가 커지면 여러 Repository 들이 `ContentEntity` 를 만들어야 할 수도 있는데, 그때 여기 있는 코드가 필요할 수도 있으니까요.

2022-10-25 11:04 UTC, FrancescoJo commented on app-infrastructure/src/main/kotlin/com/flab/hsw/core/jdbc/user/UserEntity.kt
> +    fun toUserProfile(): UserProfile = UserProfile.create(
좋습니다.

2022-10-25 11:05 UTC, FrancescoJo commented on app-infrastructure/src/main/resources/sql/data/00-user.sql
> +INSERT INTO `users` (`uuid`, `nickname`, `email`, `login_id`, `password`, `version`)
요거 테스트 반복해서 실행할 경우 문제되지는 않을까요?

2022-10-25 11:05 UTC, FrancescoJo commented on app-infrastructure/src/main/resources/sql/schema/01-content.sql
> +CREATE TABLE IF NOT EXISTS `contents`
`IF NOT EXISTS` 가 있는 이유는 뭘까요?

2022-10-25 11:05 UTC, FrancescoJo commented on app-infrastructure/src/main/resources/sql/schema/01-content.sql
> +    `description`       VARCHAR(200)  NOT NULL,
`VARCHAR` 와 `TEXT` 의 차이를 설명해주세요.

2022-10-25 11:06 UTC, FrancescoJo commented on app-infrastructure/src/test/kotlin/testcase/medium/MediumTestDataDeclarations.kt
> +    private fun List<UUID>.randomUuid(): UUID = this[Random().nextInt(this.size)]
요거 그냥 kotlin standard 함수중에 

https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/random.html

이거 쓰시면 됩니다. 불필요한 구현이에요.

2022-10-25 11:07 UTC, FrancescoJo commented on app-infrastructure/src/test/kotlin/testcase/medium/jdbc/content/ContentEntityDaoTest.kt
> +    @DisplayName("")
Test 이름이 빈약하네요. 이 테스트의 의도가 뭐죠?

2022-10-25 11:07 UTC, FrancescoJo commented on app-infrastructure/src/test/kotlin/testcase/medium/jdbc/content/ContentEntityDaoTest.kt
> +        val randomContent: ContentEntity = randomContentEntity(providerUserSeq = user.seq!!)
여기도 user 의 `seq` 가 반드시 있을거라고 생각하시는 이유가 있나요?

2022-10-25 11:10 UTC, FrancescoJo requested changes
전반적으로 코멘트 확인해주시고, 일부 수정이 필요해 보입니다.

2022-10-25 11:10 UTC, FrancescoJo commented
kotlin 의 double bang(`!!`) 은 정말 조심하라는 의미의 연산자다. 일단 `!!` 이 많이 보이는 코드는 smelly code 라고 생각하셔야 합니다. Kotlin 의 강력한 기능중 하나인 Null safety 를 무력화 하기 때문입니다.

2022-10-29 17:19 UTC, abcshc commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/content/Content.kt
> +                deleted = false,
분리된 커멘드를 통해서 엔티티를 생성할 때 기본값을 적용할 수 있도록 수정했습니다.
```kotlin
internal class ContentEntity(
  ...
  fun from(createContentCommand: CreateContentCommand, providerUserSeq: Long): ContentEntity =
    with(createContentCommand) {
        val now = Instant.now()
    
        return ContentEntity(
            url = url,
            description = description,
            providerUserSeq = providerUserSeq,
            registeredAt = now,
            lastActiveAt = now,
            deleted = false,
        )
    }
```

2022-10-29 17:20 UTC, abcshc commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/content/CreateContent.kt
> +interface CreateContent {
생성을 위한 메시지로 생성 행위를 포함시키기 위해 이름을 `CreateContentCommand`로 적용했습니다.

2022-10-29 17:20 UTC, abcshc commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/content/aggregate/ContentModel.kt
>      companion object {
중복 제거 했습니다.

2022-10-29 17:20 UTC, abcshc commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/content/aggregate/CreateContentModel.kt
> +    companion object {
중복 제거 했습니다.

2022-10-29 17:20 UTC, abcshc commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/user/UserProfile.kt
> +interface UserProfile {
처음에는 사용자의 요약 정보 또는 약력의 뜻으로 Profile을 사용했는데 [엔지니어링에서는 다른 뜻으로 사용](https://en.wikipedia.org/wiki/Profile_(engineering))될 수 있을 것 같아 Simple을 붙인 `SimpleUserProfile` 로 수정하였습니다.
선택적 기능을 정의하는 프로파일로 말씀해주신 게 맞을까요?

2022-10-29 17:20 UTC, abcshc commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/user/aggregate/UserProfileModel.kt
> +    companion object {
중복 제거 했습니다.

2022-10-29 17:20 UTC, abcshc commented on app-core/src/test/kotlin/test/domain/content/aggregate/ContentAggregateTestUtils.kt
> +fun randomCreateContent(
Companion 확장 함수로 변경했습니다. 👍

2022-10-29 17:20 UTC, abcshc commented on app-core/src/test/kotlin/testcase/small/domain/content/CreateContentUseCaseSpec.kt
> +        `when`(contentRepository.create(any())).thenAnswer {
`UseCase` 동작에 영향을 주는 항목들은 `arguments`를 통해 그대로 넘겨주고 나머지는 임의의 값이나 고정값을 넘겨주도록 했습니다.
해당 내용을 `assert` 하지 않도록 주의해야할 것 같습니다.

2022-10-29 17:20 UTC, abcshc commented on app-core/src/test/kotlin/testcase/small/domain/content/CreateContentUseCaseSpec.kt
> +            val now = Instant.now()
실제 UseCase에는 영향을 주지 않는 데이터라고 생각해서 추가했었고 실제 데이터와 비슷하게 만들고 싶어서 만들다 보니 구현이 되었네요 😓 
별도의 함수로 빼고 이름을 `randomGeneratedNow`로 지어 영향이 가는 부분만 확인할 수 있도록 수정했습니다.

2022-10-29 17:20 UTC, abcshc commented on app-infrastructure/src/main/kotlin/com/flab/hsw/core/jdbc/content/ContentEntity.kt
> +        else -> this.seq == other.seq
처음에는 UUID와 seq를 나눈 것이 단순 어플리케이션과 데이터베이스의 식별값 감추기 위함으로만 생각했던 것 같습니다. 😓 
컨텐츠를 등록일 순으로 검색하는 경우가 많을 것 같아 auto increment 되는 seq를 식별자로 사용하기로 하여 id로 변경하였고 UUID가 불필요하게 느껴져 제거했습니다.

2022-10-29 17:21 UTC, abcshc commented on app-infrastructure/src/main/kotlin/com/flab/hsw/core/jdbc/content/repository/ContentRepositoryImpl.kt
> +@Service
자주 이야기 해주셔서 익숙한 `@InfrastructureService` 로 만들었습니다.

2022-10-29 17:24 UTC, abcshc commented on app-infrastructure/src/main/resources/sql/data/00-user.sql
> +INSERT INTO `users` (`uuid`, `nickname`, `email`, `login_id`, `password`, `version`)
medium test에서만 읽어 사용하고 있기 때문에 처음 init 시 한번만 실행되고 H2 메모리 DB를 사용하고 있어 지금은 문제가 없다고 생각합니다. 하지만 데이터가 유지되는 경우 문제가 될 수 있겠네요.

아래 `IF NOT EXISTS` 와 같이 H2 MYSQL 모드에서 IGNORE가 가능해서 추가하였습니다.

2022-10-29 17:25 UTC, abcshc commented on app-infrastructure/src/main/kotlin/com/flab/hsw/core/jdbc/content/repository/ContentRepositoryImpl.kt
> +    private fun ContentEntity.toContent(providerUserEntity: UserEntity): Content {
`ContentEntity` 로 옮겼습니다. 
https://github.com/f-lab-edu/hello-study-world/pull/14#discussion_r1004338906
위 null 처리에 대해 말씀해주신 것과 같은 고민이었는데 같은 파일 안에서 처리되면 함께 읽히지 않을까 해서 굳이 옮겼었습니다. 
다음부터는 이런 고민을 하게 되면  smelly code 일 수 있다는 걸로 의심하고 원인을 해결할 방법을 찾아야겠네요.

2022-10-29 17:25 UTC, abcshc commented on app-infrastructure/src/main/resources/sql/schema/01-content.sql
> +CREATE TABLE IF NOT EXISTS `contents`
이미 테이블이 있다면 쿼리가 실패하여 서버가 실행되지 못함을 회피하기 위해 있는 것 같습니다.

2022-10-29 17:26 UTC, abcshc commented on app-infrastructure/src/test/kotlin/testcase/medium/jdbc/content/ContentEntityDaoTest.kt
> +    @DisplayName("")
`A content is inserted into the database` 로 해당 내용을 추가했습니다. 
컨텐츠를 직접 데이터베이스에 추가해보는 테스트입니다.

2022-10-29 17:26 UTC, abcshc commented on app-infrastructure/src/test/kotlin/testcase/small/ContentRepositoryImplSpec.kt
> +@SmallTest
단순 메소드 콜을 검증하는 것은 큰 의미가 없을 것 같네요... 앞으로 MediumTest로 더 상세하게 작성하겠습니다.

2022-10-30 10:09 UTC, abcshc commented on app-infrastructure/src/main/resources/sql/schema/01-content.sql
> +    `description`       VARCHAR(200)  NOT NULL,
`VARCHAR`는 최대 길이를 지정할 수 있습니다. 데이터가 테이블에 인라인으로 저장됩니다.
`TEXT`는 주로 대용량을 처리할 때 사용하는 타입입니다. 데이터가 외부 페이지에 저장됩니다.  문자열의 크기가 예측할 수 없이 큰 경우 사용합니다.

사용하는 데이터베이스, 버전, 데이터베이스 엔진, ROW_FORMAT에 따라 저장 방식이 달라질 수 있는 것 같습니다.

2022-10-30 10:12 UTC, abcshc commented on app-infrastructure/src/main/kotlin/com/flab/hsw/core/jdbc/content/repository/ContentRepositoryImpl.kt
> +        return contentEntityDao.insert(ContentEntity.from(createContent, provider.seq!!))
Auto increment로 순차적으로 증가하여 seq를 사용한 걸로 이해를 했습니다. 등록 순서대로 정렬로도 사용할 수 있고 식별값으로 사용할 수도 있습니다.

아직 기본값으로 저장여부를 판단하는 로직이 없지만 SequenceMixin을 미리 만들어 `UNIDENTIFIABLE` 기본값으로 not null로 변경하였습니다.

2022-10-30 10:20 UTC, abcshc commented on app-infrastructure/src/test/kotlin/testcase/medium/jdbc/content/ContentEntityDaoTest.kt
> +        val randomContent: ContentEntity = randomContentEntity(providerUserSeq = user.seq!!)
이전에 작성한 코드에 대한 믿음으로 사용했습니다. 😞
이번에는 not null로 바꾸어 처리했습니다. 별도의 null 처리를 만들거나 not null로 변환할 수 있도록 해야겠습니다.

2022-10-31 13:14 UTC, FrancescoJo commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/content/command/CreateContentCommand.kt
> +        @SuppressWarnings("LongParameterList")      // Intended complexity to provide various Content creation cases
불필요한 SuppressWarning 이 된것 같네요

2022-10-31 13:14 UTC, FrancescoJo commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/content/command/aggregate/CreateContentCommandModel.kt
> +internal class CreateContentCommandModel(
요거는 CreateContentCommand 내에 private data class 로 완전히 숨기는게 더 좋겠습니다.

2022-10-31 13:15 UTC, FrancescoJo commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/content/command/repository/ContentCommandRepository.kt
> +interface ContentCommandRepository {
`ContentRepository` 가 좀더 어울리는 이름 같습니다.

2022-10-31 13:15 UTC, FrancescoJo commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/content/query/aggregate/ContentModel.kt
> +internal data class ContentModel(
요 구현도 Content 파일 내의 private class 구현으로 바꿔주세요.

2022-10-31 13:16 UTC, FrancescoJo commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/user/User.kt
> +interface User : SimpleUserProfile, SoftDeletable {
좋습니다.

2022-10-31 13:17 UTC, FrancescoJo commented on app-core/src/test/kotlin/testcase/small/domain/content/CreateContentCommandUseCaseSpec.kt
> +internal class CreateContentCommandUseCaseSpec {
`CreateContentUseCase` 의 사양을 기술하는거니 이름이 `CreateContentUseCaseSpec` 이 된다면 좋겠네요.

2022-10-31 13:17 UTC, FrancescoJo commented on app-infrastructure/src/main/kotlin/com/flab/hsw/core/CoreKopringApplicationImpl.kt
> +        const val UNIDENTIFIABLE: Long = -1L
이 값은 별도의 `Identifiable<Long>` 같은 개념에 두는게 좋겠습니다.

2022-10-31 13:18 UTC, FrancescoJo commented on app-infrastructure/src/main/kotlin/com/flab/hsw/core/annotation/InfrastructureService.kt
> +annotation class InfrastructureService
좋습니다.

2022-10-31 13:20 UTC, FrancescoJo commented on app-infrastructure/src/main/kotlin/com/flab/hsw/core/jdbc/SequenceMixin.kt
> +interface SequenceMixin {
네. 여기 있는 `SequenceMixin` 은 `Identifiable` 같은 개념이 좀더 어울릴 것 같아요. 그리고 `Identifiable<Long>` 은 `UNIDENTIFIABLE = -1L` 을 가진다고 표현하는게 좀더 좋지 않을까요? 

Sequnce 가 대상읠 Identify 하는 수단은 아니니가요.

```kotlin
interface Identifiable<T> {
  val id: T

  val isIdentifiable: Boolean
}

interface LongIdentifiable<Long> {
  val id: Long

  val isIdentifiable: Boolean
    get() = id == UNIDENTIFIABLE
  
  companion object {
    const val UNIDENTIFIABLE = -1L
  }
}
```

2022-10-31 13:20 UTC, FrancescoJo commented on app-infrastructure/src/main/kotlin/com/flab/hsw/core/jdbc/content/ContentEntity.kt
> +        else -> this.seq == other.seq
그렇다면 `Content` 의 `id` 는 `Long` 타입이어야 할 것 같습니다.

2022-10-31 13:21 UTC, FrancescoJo commented on app-infrastructure/src/main/resources/sql/schema/01-content.sql
> +CREATE TABLE IF NOT EXISTS `contents`
네 그렇다면 만약 테이블 스키마를 변경해야 한다면 그때는 어떻게 하는게 좋을까요

(지금 고민할 단계는 아니지만)

2022-10-31 13:22 UTC, FrancescoJo commented on app-infrastructure/src/main/resources/sql/schema/01-content.sql
> +    `description`       VARCHAR(200)  NOT NULL,
좋습니다. 그렇다면 `url` 과 `description` 이 `VARCHAR` 보다는 `TEXT` 인게 좀더 좋지 않을까 싶네요. 

설명 조회에 LIKE 를 활용하려고 `description` 을 `VARCHAR` 로 둔건가요?

2022-10-31 13:23 UTC, FrancescoJo commented on app-infrastructure/src/test/kotlin/testcase/medium/MediumTestDataDeclarations.kt
> +        UUID.fromString("e8d1b7dd-4ca7-47ac-903f-af585c13c041"),
나중에는 이것조차 all random 으로 두면 좀더 좋겠습니다.
보통 preset data 를 쓰는건 LargeTest 단계에서 하는 편이 좋습니다.
왜냐면 MediumTest 는 setup 및 실행 속도가 비교적 빠르므로 사전에 오류를 빠르게 탐지하고 고치기 더 수월하기 때문입니다.

2022-10-31 13:24 UTC, FrancescoJo commented on app-infrastructure/src/test/kotlin/testcase/medium/jdbc/content/ContentEntityDaoTest.kt
> +        val user = userEntityDao.selectByUuid(randomUuidFromUserEntityData())!!
좋습니다.

2022-10-31 13:24 UTC, FrancescoJo commented on app-infrastructure/src/test/kotlin/testcase/medium/jdbc/user/UserEntityDaoTest.kt
> +        val updatedUser = sut.update(foundUser.seq, foundUser)
Identifiable 과 Sequence 를 구분해서 `seq` 보다는 `id` 가 되어야겠죠?

2022-10-31 13:25 UTC, FrancescoJo commented on app-infrastructure/src/test/kotlin/testcase/small/ContentCommandRepositoryImplSpec.kt
> +class ContentCommandRepositoryImplSpec {
`ContentCommandRepositoryImplSpec` 보다는 `ContentCommandRepositorySpec` 이라고 이름 짓는게 더 좋겠습니다.

`sut` 의 타입도 `ContentCommandRepository` 로 두시죠.

나중에 Repository 내부의 특수한 구현 (Cache 타이밍을 컨트롤 한다던지 등) 같은게 생기기 전까지는 impl 타입을 최대한 모르도록 작성하는 편이 테스트를 좀더 유연하게 할 수 있습니다.

2022-10-31 13:26 UTC, FrancescoJo commented on app-infrastructure/src/test/kotlin/testcase/small/ContentCommandRepositoryImplSpec.kt
> +            { assertThat(createdContent.seq, not(Matchers.nullValue())) },
이런거 작성하기 매우 짜증나는데 좋은 방법은 없을까요?

2022-10-31 13:26 UTC, FrancescoJo commented on app-infrastructure/src/test/kotlin/testcase/medium/MediumTestDataDeclarations.kt
> +        UUID.fromString("e8d1b7dd-4ca7-47ac-903f-af585c13c041"),
즉, Repository 를 이용해 Random content 를 저장하는 로직을 만들고,

저장 이후 다시 조회가 가능한지 같은 '적당한' 규모의 Integration test 를 만드는 거죠.

2022-11-02 04:09 UTC, leeho1110 approved these changes

2022-11-04 18:18 UTC, abcshc commented on app-infrastructure/src/test/kotlin/testcase/small/ContentCommandRepositoryImplSpec.kt
> +            { assertThat(createdContent.seq, not(Matchers.nullValue())) },
[테스트용 하위 클래스](http://xunitpatterns.com/Test-Specific%20Subclass.html)를 만들까 생각했는데 아직 중복된 코드가 없고 현재 테스트에 불필요한 구현이 필요해서 (`fun delete()`) 우선 그대로 두었습니다.

2022-11-05 12:15 UTC, FrancescoJo commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/content/query/Content.kt
> +    val registeredAt: Instant
`registeredAt`, `lastUpdatedAt` 같은 속성들은 둘이 함께 존재할 가능성이 매우 높을 것 같아요.

mixin 으로 빼는건 어떨까요?

2022-11-05 12:17 UTC, FrancescoJo commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/content/query/Content.kt
> +    val provider: SimpleUserProfile
Content 가 User 를 가지는게 맞을지, 그게 아니라서 SImpleUser 를 연결한 거겠지만

이 경우 SimpleUserProfile 을 만들기 어렵다면 Content 를 만들때 SimpleUserProfile 을 만드는 수고가 추가로 듭니다.

user id 를 'tag' 같은 개념으로 두거나, `SimpleUserProfile` 을 `UserTag` 같은 태그 타입 (id 와 이름 등 간단한 식별 정보만 있는) 으로 아주 간략하게 구현하는것도 좋을 것 같습니다.

2022-11-05 12:18 UTC, FrancescoJo commented on app-infrastructure/src/main/kotlin/com/flab/hsw/core/jdbc/content/ContentEntity.kt
> +internal class ContentEntity(
Entity 는 가급적 `var` 로 mutable 로 두는게 Repository 구현을 좀더 수월하게 할 수 있을 것 같습니다.

2022-11-05 12:19 UTC, FrancescoJo commented on app-infrastructure/src/main/kotlin/com/flab/hsw/core/jdbc/user/dao/UserEntityDao.kt
> +            id = super.doInsertAndGetId(UserEntity.COL_SEQ, sql) {
`COL_SEQ` 라는 이름이 거슬리네요.

2022-11-05 12:20 UTC, FrancescoJo commented on app-infrastructure/src/test/kotlin/testcase/small/ContentRepositorySpec.kt
> +class ContentRepositorySpec {
이 테스트 의미 없습니다. 메모리 캐시같은 상태 확인하실 거 아니라면 @MediumTest 로 올려주세요.

2022-11-10 04:49 UTC, abcshc commented on app-infrastructure/src/main/kotlin/com/flab/hsw/core/jdbc/content/ContentEntity.kt
> +internal class ContentEntity(
전체를 `var`로 바꾸진 않았고 변경되지 않을 프로퍼티들은 그대로 `val` 두었습니다.

2022-11-10 04:50 UTC, abcshc commented on app-infrastructure/src/main/kotlin/com/flab/hsw/core/jdbc/user/dao/UserEntityDao.kt
> +            id = super.doInsertAndGetId(UserEntity.COL_SEQ, sql) {
UserEntity의 컬럼도 모두 id로 변경했습니다.

2022-11-10 04:51 UTC, abcshc commented on app-infrastructure/src/test/kotlin/testcase/small/ContentRepositorySpec.kt
> +class ContentRepositorySpec {
기존 테스트에서 mock 부분을 제거하면서 `JdbcTemplateMediumTestBase`를 상속받아 `MediumTest`로 동작할 수 있도록 수정하였습니다.

2022-11-10 11:48 UTC, FrancescoJo approved these changes
고생 많으셨습니다 =3 =3

2022-11-16 05:27 UTC, merged