#10 사용자가 회원가입 시 전달한 비밀번호를 암호화된 형태로 저장하라 구현
f-lab-edu/hello-study-world pull request #16
Opened 2022-10-25 08:18 UTC by leeho1110

### Context and motivation
- 사용자가 회원가입 시 입력한 비밀번호를 암호화된 형태로 저장하기 위한 기능을 구현합니다.

---

### Key implements
- `bcrypt`암호화 방식을 활용해 사용자의 패스워드가 암호화된 형태로 저장됩니다.
- RestDocs의 SnippetException 예외가 발생하지 않도록 수정했습니다.

2022-10-25 11:11 UTC, FrancescoJo commented
Github reviewer, assignee 설정해 주셔야 reviewer 들에게 알림이 갑니다.

우측의 Reviewers 와 Assignee 를 설정해 주세요.

2022-10-25 11:14 UTC, FrancescoJo commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/user/usecase/CreateUserUseCase.kt
> +            password = BCrypt.hashpw(message.password, BCrypt.gensalt())
추후 `CreateUserUseCase` 가 아니라, `LoginWithIdPasswordUseCase` 에서도 이 로직이 필요할 것 같은데요,

> '우리의 패스워드 암호화 정책은 `BCrypt.hashpw(plaintext, BCrypt.gensalt())` 로직을 호출하는 것

이라고 *정책* 으로 정의해 주시기 바랍니다. 그리고 salt 가 다르더라도 hash 결과값에 문제가 없을까요?

2022-10-25 11:14 UTC, FrancescoJo requested changes
암호화 정책 구현 필요

2022-10-25 12:48 UTC, leeho1110 commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/user/usecase/CreateUserUseCase.kt
> +            password = BCrypt.hashpw(message.password, BCrypt.gensalt())
> _추후 CreateUserUseCase 가 아니라, LoginWithIdPasswordUseCase 에서도 이 로직이 필요할 것 같은데요,_

네! 패스워드 암호화 정책은 단순 라이브러리 호출이 아닌 암호화 정책을 수행 책임을 갖는 객체를 생성해 처리하도록 재구현하겠습니다.

---

> _그리고 salt 가 다르더라도 hash 결과값에 문제가 없을까요?_
BCrypt 내부 구현을 디버깅하여 파악한 내용은 아래와 같습니다.
1. 동일한 plain text에 대한 `real_salt`는 항상 같습니다.
2. 이 `real_salt`는 salt값이 다르더라도 내부 로직을 통해 추출이 가능합니다.

따라서 만약 salt값이 달라지더라도 내부 plain_text에 매칭된 `real_salt`는 항상 동일하므로 궁극적으로 **패스워드 일치를 판단하는 것에는 문제가 없다**고 판단했습니다.

2022-10-27 12:16 UTC, FrancescoJo commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/user/aggregate/PasswordEncryptor.kt
> +        fun newInstance(): PasswordEncryptor = PasswordEncryptorImplByBCrypt()
좋습니다

2022-10-27 12:17 UTC, FrancescoJo commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/user/usecase/CreateUserUseCase.kt
> +            passwordEncryptor = PasswordEncryptor.newInstance()
이거도 `newInstance` 시점에 주입받을 수 있도록 해 주시고, 거기의 기본 함수 인자로 선언하시는게 좋겠어요.

이렇게 하시면 `PasswordEncryptor` 를 `CreateUserUseCase` 테스트 시점에 주입하기 어렵습니다.

2022-10-27 12:18 UTC, FrancescoJo commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/user/usecase/CreateUserUseCase.kt
> +            password = BCrypt.hashpw(message.password, BCrypt.gensalt())
좋습니다. 확인 감사합니다

2022-10-27 12:18 UTC, FrancescoJo commented on app-core/src/test/kotlin/testcase/small/domain/user/CreateUserUseCaseSpec.kt
> +            { assertThat(BCrypt.checkpw(message.password, createdUser.password), `is`(true)) }
여기 코드중복을 PasswordEncryptor 를 이용한것과 실제결과가 같다... 는 식으로 테스트를 수정해주세요

2022-10-27 16:42 UTC, leeho1110 commented on app-core/src/test/kotlin/testcase/small/domain/user/CreateUserUseCaseSpec.kt
> +            { assertThat(BCrypt.checkpw(message.password, createdUser.password), `is`(true)) }
넵, PassworkEncrytor 활용 여부와 무관하게 테스트 본래 목적인 `메시지를 완벽하게 표현하는 객체가 생성` 되도록 수정하겠습니다.

2022-10-29 04:08 UTC, FrancescoJo commented on app-core/src/test/kotlin/testcase/small/domain/user/CreateUserUseCaseSpec.kt
> +            { assertThat(equalsWhetherPasswordIsEncryptedOrNot(message.password, createdUser.password), `is`(true))}
Custom assertion 이 나쁜건 아니지만 저라면 sut 를 이런 식으로 구성하고 이 라인의 assertion 을 이렇게 수정할 것 같습니다.

```kotlin
class CreateUserUseCaseSpec {
  private lateinit var userRepository: UserRepository,
  private lateinit var passwordEncryptor: PasswordEncryptor
  private lateinit var sut: CreateUserUseCase

  @BeforeEach
  fun setup() {
    this.userRepository = mock()
    passwordEncryptor = PasswordEncryptor.newInstance()
    this.sut = CreateUserUseCase.newInstance(userRespository, passwordEntryptor)
  }

  // ...
  assertAll(
    // ...
    // CreateUser 시점에 넘긴 password 의 plaintext 를 활용
    { assertThat(createdUser.password, `is`(passwordEncryptor.encrypt(plainTextPassword))) }
  )
}
```

2022-10-29 04:09 UTC, FrancescoJo commented on app-core/src/test/kotlin/testcase/small/domain/user/CreateUserUseCaseSpec.kt
> +            { assertThat(equalsWhetherPasswordIsEncryptedOrNot(message.password, createdUser.password), `is`(true))}
또는 이렇게도 구성하실 수 있습니다.

```kotlin
  { verify(passwordEncryptor, times(1)).encrypt(plainTextPassword) }
```

2022-10-29 04:10 UTC, FrancescoJo requested changes
Test 만 수정해주세요

2022-10-29 07:09 UTC, leeho1110 commented on app-core/src/test/kotlin/testcase/small/domain/user/CreateUserUseCaseSpec.kt
> +            { assertThat(equalsWhetherPasswordIsEncryptedOrNot(message.password, createdUser.password), `is`(true))}
`BCrypt.hashpw()`는 동일한 plainText에 대해서 다른 salt값을 반환(real_salt는 숨겨져 매칭은 가능)하기 때문에 첫 번째 의견은 테스트 통과가 어려울 것으로 보입니다. 

따라서 두 번째 PasswordEncrytor Mocking을 통해 검증하도록 수정하겠습니다.

2022-10-29 07:57 UTC, FrancescoJo approved these changes
고생하셨습니다

2022-10-29 15:16 UTC, abcshc approved these changes

2022-10-29 15:17 UTC, merged