#12 학습 컨텐츠의 선호도를 표현할 수 있도록 `추천 기능` 도메인 모델을 구현하라
f-lab-edu/hello-study-world pull request #18
Opened 2022-11-03 12:47 UTC by leeho1110

### Context and motivation
- 학습 컨텐츠의 퀄리티가 사용자로부터 판단되기 위해 필요합니다.
- 사용자가 컨텐츠를 추천하는 `추천 기능`의 도메인 모델을 구현합니다.

---

### Key implements
- 회원의 `추천`을 생성하는 유즈케이스, 도메인 모델, `Recommend`를 구현했습니다. 
- `CreateRecommendUseCase` 내부에서는 **추천인(`recommender`)이 반드시 존재**한다고 가정하는 상태로 작성했습니다. 

---

### Notes
- ***Q. 회원 정보가 어디에 존재하더라도(ex.Memory DB, Server session) 유즈케이스가 영향을 받지 않아야 한다고 판단했습니다. 적절할까요?***
    - `추천` 기능 호출은 로그인을 통해 인증된 회원만 가능합니다.
    - 인증된 회원(추천인) 정보 추출은 컨트롤러 레이어의 역할이라고 판단했습니다.

2022-11-05 12:25 UTC, FrancescoJo commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/content/Recommend.kt
> +interface Recommend {
'누구에게' '어떤' 추천을 제공하는건가요?

2022-11-05 12:27 UTC, FrancescoJo commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/content/repository/ContentRepository.kt
> +    fun findRecommendHistoryByUserIdAndContentId(recommend: Recommend): Recommend?
함수 이름과 parameter 가 일치하지 않네요

2022-11-05 12:28 UTC, FrancescoJo commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/content/repository/ContentRepository.kt
> +    fun findRecommendHistoryByUserIdAndContentId(recommend: Recommend): Recommend?
`Content` 타입을 다루는 Repository 에 `Recommend` 타입을 다루는 기능을 넣는게 괜찮을까요?

2022-11-05 12:30 UTC, FrancescoJo commented on app-core/src/test/kotlin/testcase/small/domain/content/CreateRecommendUseCaseSpec.kt
> +            { verify(contentRepository, times(1)).saveRecommendHistory(any()) }
이 verify 는 뭐, 굳이 지울 필요는 없지만 테스트 시나리오 이름대로라면 없어도 무방할것 깉긴 합니다.

2022-11-05 12:31 UTC, FrancescoJo requested changes
큰 문제는 없는것 같은데, 네이밍과 ContentRepository 의 역할에 대해 한번 더 생각해 주세요.

2022-11-06 06:06 UTC, leeho1110 commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/content/Recommend.kt
> +interface Recommend {
넵 환님 의견이 좀더 직관적인 변수명으로 보여지네요. 수정하겠습니다.

2022-11-06 06:09 UTC, leeho1110 commented on app-core/src/main/kotlin/com/flab/hsw/core/domain/content/repository/ContentRepository.kt
> +    fun findRecommendHistoryByUserIdAndContentId(recommend: Recommend): Recommend?
> 함수 이름과 parameter 가 일치하지 않네요

그렇네요 :sweat_smile: 수정하겠습니다.

--- 

> `Content` 타입을 다루는 Repository 에 `Recommend` 타입을 다루는 기능을 넣는게 괜찮을까요?

큰 틀 안에서는 `Recommend` 타입도 `Content` 와 같이 묶어야 하지 않을까 생각했었는데요. 말씀대로 Repository는 하나의 타입만 다루는게 좋을 것 같아요. 분리하도록 하겠습니다.

2022-11-07 11:55 UTC, merged