로그인을 위한 토큰을 관리하는 토큰 관리자 객체를 구현하라
f-lab-edu/hello-study-world pull request #32
Opened 2022-12-17 04:15 UTC by leeho1110

### Context and motivation

- #29 세부 사항입니다.
- #30  기능 구현입니다. 

---

### Key implements

- Json Web Token 핸들링을 위해 [jjwt(Java JWT) 라이브러리](https://github.com/jwtk/jjwt)를 사용했습니다.
- RSA 대칭키 방식을 사용해 Access Token 을 암복호화합니다.

---

### Notes

- properties 파일로 주입중인 키 쌍은 추후 비공개 처리할 예정입니다.
    - 위 과정 구현으로 인해 전체 병목이 생겨 우선 분리합니다.
- #31 을 위해 선행되어야 하는 PR입니다.

2022-12-19 07:12 UTC, FrancescoJo commented
Git 에는 history 가 남기 때문에 key 처럼 민감한 정보는 아예 commit 안되도록 하는 편이 좋습니다. 왠만하면 이 PR 내에서 해결하는게 좋겠어요.

2022-12-19 07:13 UTC, FrancescoJo commented on app-main/src/main/kotlin/com/flab/hsw/util/JwtTokenManager.kt
> +    fun createBy(loginSuccessUser: User): String {
이 로직은 그럼 Login 이라는 기능에서 활용하게 되나요?

2022-12-19 07:13 UTC, FrancescoJo commented on app-main/src/test/kotlin/test/endpoint/v1/user/AuthTestSupport.kt
> +    keyPairGenerator.initialize(2048)
1. 왜 RSA 2048 을 쓸까요?
2. 이 값은 외부 주입으로 변경할 수 없을까요?

2022-12-19 07:20 UTC, FrancescoJo reviewed
큰 문제는 없어 보입니다만, 몇가지 의문 사항만 해결해 주시기 바랍니다.

2022-12-19 12:38 UTC, leeho1110 commented on app-main/src/main/kotlin/com/flab/hsw/util/JwtTokenManager.kt
> +    fun createBy(loginSuccessUser: User): String {
네! `UserLoginControllerImpl.login` [Link](https://github.com/f-lab-edu/hello-study-world/pull/34/commits/541acc89a9574290691fdb6010aa9730e663161f)에서 사용됩니다!

2022-12-19 15:49 UTC, leeho1110 commented on app-main/src/test/kotlin/test/endpoint/v1/user/AuthTestSupport.kt
> +    keyPairGenerator.initialize(2048)
1. 가장 간단한 이유로는 **[RFC 7518](https://www.rfc-editor.org/rfc/rfc7518#page-6)에서 RS256 알고리즘을 권장**하고 있기 때문입니다. 
2. 키 쌍을 `JAVA_OPTS`를 통해 외부에서 주입할 수 있을 것 같습니다.

2022-12-20 12:09 UTC, FrancescoJo commented on app-main/src/test/kotlin/test/endpoint/v1/user/AuthTestSupport.kt
> +    keyPairGenerator.initialize(2048)
좋습니다! 잘 기억해 두셨다가 나중에 활용하세요!

2022-12-26 10:56 UTC, FrancescoJo commented on app-main/src/main/kotlin/com/flab/hsw/endpoint/auth/AuthenticationController.kt
> +interface AuthenticationController {
이 Endpoint 는 불필요한것 같은데요...? 필요하다면 Test 아래에 구현하는게 맞을 것 같아요.

2022-12-26 10:56 UTC, FrancescoJo requested changes
Public Key 를 반환하는 Endpoint 는 필요없다고 논의했던 것으로 기억합니다. 제거하는게 좋겠네요.

2022-12-27 15:32 UTC, leeho1110 commented on app-main/src/main/kotlin/com/flab/hsw/endpoint/auth/AuthenticationController.kt
> +interface AuthenticationController {
넵! 모르고 #31 브랜치에 삭제 작업을 진행했군요 😅 ,, 현 브랜치에 커밋했습니답

2022-12-28 05:37 UTC, FrancescoJo approved these changes
고생하셨습니다.

2022-12-31 12:30 UTC, merged