Feature/#31 add auth check interceptor production
f-lab-edu/hello-study-world pull request #34
Opened 2022-12-18 12:19 UTC by leeho1110

### Context and motivation

- #29 세부 사항입니다.
- #31 기능 구현입니다. 

---

### Key implements

- 어노테이션 기반으로 인증이 필요한 핸들러를 구별합니다.
- JwtTokenManager, Spring interceptor를 활용해 핸들러 진입 전 인증 프로세스를 진행합니다.
- Globla ExceptionHandler & Contract 객체를 예외를 핸들링합니다.

---

### Notes

- #30 이 `Master` 브랜치에 커밋되기 전까지 detekt & test CI는 일시중지합니다.
- #32 에 해당된 커밋을 제외한 File Changes는 12개입니다.

2022-12-19 07:21 UTC, FrancescoJo reviewed
이전 구현이랑 PR 내용이 중복되네요

2022-12-19 08:17 UTC, FrancescoJo commented on app-main/src/main/kotlin/com/flab/hsw/util/JwtTokenManager.kt
> +            .parseClaimsJws(token.removePrefix(BEARER_PREFIX))
1. token 에 "asdfsadfasfasadgojasdlkgasd" 같은 이상한 문자열 또는 빈 문자열이 들어온다면 어떻게 될까요?
2. `removePrefix` 호출 결과가 인코딩한 jwt 형식이 아니라면 어떤 에러가 발생하고, 어떻게 처리해야 5xx 에러가 아닌 4xx 에러로 치환할 수 잇을까요?

2022-12-19 08:18 UTC, FrancescoJo commented on app-main/src/main/kotlin/com/flab/hsw/interceptor/AuthenticationInterceptor.kt
> +    private fun shouldAuthenticated(handler: Any) = handler is HandlerMethod
좋습니다. ㅎ 이 구현덕에 이제 `@MustAuthenticated` 어노테이션이 달린 메소드에만 인증 로직이 동작하겠네요.

2022-12-19 08:19 UTC, FrancescoJo commented on app-main/src/main/kotlin/com/flab/hsw/exception/UnauthorizedException.kt
> +        const val EXPIRED_TOKEN_DESC = "만료된 토큰입니다."
12 - 14 라인 const 는 이 파일 내에서 안 쓰네요. 의존성을 한군데로 모으는게 좋지 않을까요?

2022-12-19 08:20 UTC, FrancescoJo commented on app-main/src/main/kotlin/com/flab/hsw/endpoint/v1/user/login/UserLoginControllerImpl.kt
> +        response.addHeader(AUTHORIZATION_HEADER, jwtTokenManager.createBy(loginSuccessUser))
이렇게 구현할 경우 클라이언트와 어떻게 커뮤니케이션 하는게 좋을지도 생각해 보시기 바랍니다.

2022-12-19 08:24 UTC, FrancescoJo commented on app-main/src/main/kotlin/com/flab/hsw/endpoint/v1/content/recommend/CreateContentRecommendationControllerImpl.kt
> +        val authorizedLoginId = servletRequest.getAttribute(User.AUTHORIZED_USER_ID_ALIAS) as String
이제 모든 컨트롤러에 이런 로직이 들어갈텐데, `HttpServletRequest` 의존성을 배제하고 아예 로그인한 이용자의 id 를 컨트롤러 파라미터로 받는 방법이 없을까요?

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/method/support/HandlerMethodArgumentResolver.html

이것과 관련된 검색을 해 보시고, 구현을 한번 바꿔보시죠.

2022-12-19 08:25 UTC, FrancescoJo commented on app-main/src/main/kotlin/com/flab/hsw/endpoint/v1/content/recommend/CreateContentRecommendationControllerImpl.kt
> +        val authorizedLoginId = servletRequest.getAttribute(User.AUTHORIZED_USER_ID_ALIAS) as String
+ 또는, AOP 를 쓰는 것도 좋을 것 같습니다만, 난이도가 갑자기 훅 올라갈테니 천천히 하셔도 됩니다.

2022-12-19 08:26 UTC, FrancescoJo commented on app-main/src/main/kotlin/com/flab/hsw/endpoint/MustAuthenticated.kt
> + * <p>이 어노테이션이 작성된 핸들러 메서드는 클라이언트의 요청을 처리할 때 반드시 인증을 필요로 합니다.</p>
1. kdoc 형식은 Markdown 과 비슷합니다.
2. 왜 그렇게 동작하는지 근거를 link 로 남겨두면 더욱 좋습니다.

2022-12-19 08:31 UTC, FrancescoJo commented on app-main/src/main/kotlin/com/flab/hsw/advice/errorhandler/LoginExceptionHandlerContractImpl.kt.kt
> +internal class JwtExceptionHandlerContractImpl (
이런 식의 구현이 나쁜 건 아니지만 예외 타입이 늘어날 수록 구현이 점점 늘어나서,

`ExceptionHandlerContract` 를 참조하는 어떤 환경설정의 constructor 가 길어지게 될텐데요.

어떻게 해결하는게 좋을까요?

https://dzone.com/articles/9-best-practices-to-handle-exceptions-in-java

2022-12-19 08:31 UTC, FrancescoJo requested changes
코멘트 확인해주세요.

2022-12-19 16:16 UTC, leeho1110 commented on app-main/src/main/kotlin/com/flab/hsw/endpoint/MustAuthenticated.kt
> + * <p>이 어노테이션이 작성된 핸들러 메서드는 클라이언트의 요청을 처리할 때 반드시 인증을 필요로 합니다.</p>
1. 자연스럽게 Markdown처럼 작성했네요. <p> 태그를 지원하지 않는 걸 깜빡했네요 😅 
2. Spring Interceptor에 대한 내용을 추가하겠습니다.

2022-12-19 16:20 UTC, leeho1110 commented
> 이전 구현이랑 PR 내용이 중복되네요

네 😢  이전 PR을 빠르게 리뷰하고 병합했어야 했는데, 그러지 못했습니다. PR을 짧게 올리고 병합까지의 기간을 짧게 가져갈 수 있도록 하겠습니다.

2022-12-23 15:10 UTC, leeho1110 commented on app-main/src/main/kotlin/com/flab/hsw/util/JwtTokenManager.kt
> +            .parseClaimsJws(token.removePrefix(BEARER_PREFIX))
token에 null 혹은 비정상적 문자열이 발생하는 경우 `IllegalArgumentException` 혹은 `MalformedJwtException` 예외가 발생합ㄴ다. 이를 `JwtExceptionHandlerContractImpl` 에서 핸들링할 수 있도록 수정하겠습니다.

2022-12-23 16:09 UTC, leeho1110 commented on app-main/src/main/kotlin/com/flab/hsw/endpoint/auth/AuthenticationController.kt
> +    override fun key() = SimpleResponse(jwtTokenManager.returnEncodedPublicKey())
테스트 케이스에서 공개키를 제공하고자 추가했었습니다. 이 경우 별도의 키페어를 생성해 처리하면 될 것 같네요. 제거하겠습니다.

2022-12-23 17:18 UTC, leeho1110 commented on app-main/src/main/kotlin/com/flab/hsw/endpoint/v1/user/login/UserLoginControllerImpl.kt
> +        response.addHeader(AUTHORIZATION_HEADER, jwtTokenManager.createBy(loginSuccessUser))
`HttpServletResponse`를 통해 토큰만 반환하는 케이스보다 명시적으로 인증 토큰에 대한 정보가 드러나나도록 수정했습니다.

2022-12-25 13:00 UTC, leeho1110 commented on app-main/src/main/kotlin/com/flab/hsw/endpoint/v1/content/recommend/CreateContentRecommendationControllerImpl.kt
> +        val authorizedLoginId = servletRequest.getAttribute(User.AUTHORIZED_USER_ID_ALIAS) as String
Spring에서 제공하는 `HandlerMethodArgumentResolver`을 통해 반복되는 ServletRequset 접근 로직을 없애도록 수정했습니다.

`CreateContentRecommendationRequest` 객체의 프로퍼티에 추천 회원의 LoginId를 추가할까 고민했습니다. 하지만 `RequestResponseBodyMethodProcessor`를 통해 `HttpMessageConverter`에게 인수 반환이 위임되는 형태로 동작하는 기존 형태를 변형시켜 작업하는 것은 난이도가 높아 추후 도전해보겠습니다. 🥲

2022-12-26 10:58 UTC, FrancescoJo commented on app-main/src/main/kotlin/com/flab/hsw/interceptor/AuthenticatedUserArgumentResolver.kt
> +    ): Any? =  (webRequest.nativeRequest as HttpServletRequest).getAttribute(AUTHORIZED_USER_ID_ALIAS) as String
```kotlin
getAttribute(AUTHORIZED_USER_ID_ALIAS) as String
```

구문은 만약 다른 로직에서 setAttribute 를 까먹으면 바로 NPE 를 발생시키니, 다음과 같이 구현해 주시기 바랍니다.

```kotlin
getAttribute(AUTHORIZED_USER_ID_ALIAS) as? String
```

2022-12-26 10:59 UTC, FrancescoJo commented on app-main/src/main/kotlin/com/flab/hsw/util/JwtTokenManager.kt
> +        val expireTime: Instant = Instant.now().plusSeconds(7200L)
여기 7200 이라는 값도 `@Value` 로 주입받도록 구현해 주세요.

2022-12-26 11:00 UTC, FrancescoJo commented on app-main/src/test/kotlin/testcase/medium/MockMvcMediumTestBase.kt
> +        "${KopringApplication.PACKAGE_NAME}.interceptor",
참고: 좋은 습관이긴 한데, 이 경우에는 `${KopringApplication.PACKAGE_NAME}` 만 지정할 경우 `${KopringApplication.PACKAGE_NAME}.*.*` 로 시작하는 모든 package 들을 scan 하게 할 수 있습니다.

2022-12-26 11:01 UTC, FrancescoJo requested changes
PR 분리 고생하셨습니다. 몇부분만 더 고쳐주세요.

2022-12-27 15:34 UTC, leeho1110 commented on app-main/src/main/kotlin/com/flab/hsw/interceptor/AuthenticatedUserArgumentResolver.kt
> +    ): Any? =  (webRequest.nativeRequest as HttpServletRequest).getAttribute(AUTHORIZED_USER_ID_ALIAS) as String
그렇겠네요! 그 점은 생각하지 못했네요 감사합니다! 수정하겠습니다.

2022-12-27 16:25 UTC, leeho1110 commented on app-main/src/main/kotlin/com/flab/hsw/util/JwtTokenManager.kt
> +        val expireTime: Instant = Instant.now().plusSeconds(7200L)
넵!~

2022-12-28 05:41 UTC, FrancescoJo commented on app-main/src/main/kotlin/com/flab/hsw/interceptor/AuthenticatedUserArgumentResolver.kt
> +class AuthenticatedUserArgumentResolver: HandlerMethodArgumentResolver {
좋습니다!

2022-12-28 05:42 UTC, FrancescoJo commented on app-main/src/main/resources/application.yml
> +    expiredPeriod: 7200
좋아요.

2022-12-28 05:42 UTC, FrancescoJo approved these changes
좋습니다. 이제 `@Disabled` Test 들을 실행해 볼 차례겠군요.

2022-12-31 12:31 UTC, merged