#4 `회원가입` Usecase 구현
f-lab-edu/hello-study-world pull request #8
Opened 2022-10-16 07:19 UTC by leeho1110

### Context and motivation
- 회원 기반 시스템을 운용하기 위한 `회원가입` 기능을 구현합니다.

---

### Key implements
- `loginId`, `password` 프로퍼티 및 정규식 추가

---

### Notes
- 정규식 추가 시 의존성이 중심쪽으로 향하도록 User 도메인 객체 내부에 선언하였습니다.

2022-10-16 10:02 UTC, FrancescoJo commented
File changes 가 24 정도나 되는 원인잉 뭐였을까요?

2022-10-16 10:20 UTC, FrancescoJo commented on app-core/src/test/kotlin/testcase/small/domain/user/CreateUserUseCaseSpec.kt
> +            { assertThat(createdUser.password, `is`(message.password)) },
비밀번호 암호화 안하고 평문으로 그대로 저장하나요?

2022-10-16 10:21 UTC, FrancescoJo commented on app-core/src/test/kotlin/test/domain/user/UserTestUtils.kt
> +    loginId: String = "",
[UserAggregateTestUtils.kt](https://github.com/f-lab-edu/hello-study-world/pull/8/files#diff-b7c0c21e53e60cde537371fce582bbe5aade61f9895e51eb9773c022052a70bb)] 여기서는 Fake value 들을 주입해줬는데,

이 수정에서는 그렇게 하지 않은 의도가 있나 궁금합니다.

2022-10-16 10:21 UTC, FrancescoJo commented on app-core/src/test/kotlin/testcase/small/domain/user/CreateUserUseCaseSpec.kt
> +    @DisplayName("Login Id must not be duplicated")
한국어로 작성하셔도 무방합니다 ㅎ

2022-10-16 10:22 UTC, FrancescoJo commented on app-infrastructure/src/main/kotlin/com/flab/hsw/core/jdbc/user/repository/UserRepositoryImpl.kt
> +    val loginIdToUserCache = FastCollectedLruCache.create<String, User>(CACHE_CAPACITY)
이런 식의 Memory cache 사용시 주의해야 할 점이 뭐가 있을까요?

2022-10-16 10:23 UTC, FrancescoJo commented on app-infrastructure/src/test/kotlin/testcase/medium/jdbc/user/UserEntityDaoTest.kt
> +import org.junit.jupiter.api.*
요거 detekt 통과 하던가요?

2022-10-16 10:23 UTC, FrancescoJo commented on app-infrastructure/src/test/kotlin/testcase/medium/jdbc/user/UserEntityDaoTest.kt
> +        @DisplayName("loginId")
이게 뭐죠? 이 테스트는 무슨 의도인지 명확하게 기술해 주시기 바랍니다.

2022-10-16 10:24 UTC, FrancescoJo commented on app-infrastructure/src/test/kotlin/testcase/small/UserRepositoryImplSpec.kt
> +        @DisplayName("exact loginId")
테스트 의도를 명확하게 적어주세요. 시나리오를 보니 "캐시하지 않은 이용자를 logIn id 로 검색하면, dao 로부터 조회한다" 인것 같네요. 맞나요?

2022-10-16 10:25 UTC, FrancescoJo commented on app-main/src/main/kotlin/com/flab/hsw/endpoint/v1/user/common/UserResponse.kt
> +        const val DESC_ID = "This is user's id."
영작이 어렵다면 한국어로 적어주셔도 됩니다 :)

2022-10-16 10:26 UTC, FrancescoJo commented on app-main/src/test/kotlin/testcase/large/endpoint/v1/user/CreateUserApiSpec.kt
> +        @DisplayName("Login Id is duplicated")
.... 하면, .... 한다 형식으로 적어주세요. 

"같은 login id 로 이용자를 중복 생성하려 하면, USER_BY_LOGIN_ID_DUPLICATED 오류가 발생한다"

2022-10-16 10:27 UTC, FrancescoJo commented
Test 를 large 와 medium, small 로 분리한 의도는 이해하셨나요?

2022-10-16 10:27 UTC, FrancescoJo approved these changes
테스트 `@DisplayName` 수정 필요

2022-10-16 10:27 UTC, FrancescoJo requested changes
Test 수정 필요

2022-10-16 13:12 UTC, leeho1110 commented
> 



> File changes 가 24 정도나 되는 원인잉 뭐였을까요?

2개의 커밋이 각각 16개, 11개 정도의 file change를 갖습니다. 커밋을 각각의 이슈로 분리했다면 파일 체인지가 나눠졌을 것 같습니다.

2022-10-16 13:13 UTC, leeho1110 commented on app-core/src/test/kotlin/testcase/small/domain/user/CreateUserUseCaseSpec.kt
> +            { assertThat(createdUser.password, `is`(message.password)) },
비밀번호 암호화 기능은 별도 이슈로 추가할 예정입니다!~

2022-10-16 13:14 UTC, leeho1110 commented on app-core/src/test/kotlin/test/domain/user/UserTestUtils.kt
> +    loginId: String = "",
누락된 듯 하네요,, 추가하겠습니다

2022-10-16 13:19 UTC, leeho1110 commented on app-infrastructure/src/test/kotlin/testcase/medium/jdbc/user/UserEntityDaoTest.kt
> +        @DisplayName("loginId")
`SavedUserMustBeFoundBy` 이너 클래스의 @DisplayName이 **Inserted user must be found for criteria:** 로 작성되어 클래스 내부의 테스트는 ':' 뒤 단어를 기재하는 형태로 작성했습니다. 

하지만 커밋 내 파일 체인지에서는 환님 의견처럼 문맥이 없어 의도 파악이 어려워보이네요. 의도가 명확히 보이도록 수정하겠습니다.

2022-10-16 13:22 UTC, leeho1110 commented on app-infrastructure/src/test/kotlin/testcase/small/UserRepositoryImplSpec.kt
> +        @DisplayName("exact loginId")
네 맞습니다. 해당 테스트 역시 커밋 내 파일 체인지만 보더라도 의도가 명확하게 보이도록 수정하겠습니다.

2022-10-16 13:26 UTC, leeho1110 commented
>

> Test 를 large 와 medium, small 로 분리한 의도는 이해하셨나요?

Spring Boot에서 제공하는 슬라이스 테스트처럼 테스트별 검증 범위를 (L,M,S으로) 분리 및 그룹핑하여 **개발 생산성을 향상시키려는 의도**로 이해하고 있습니다.

2022-10-16 13:29 UTC, leeho1110 commented on app-main/src/test/kotlin/testcase/large/endpoint/v1/user/CreateUserApiSpec.kt
> +        @DisplayName("Login Id is duplicated")
네 수정하겠습니다!~

2022-10-17 00:23 UTC, FrancescoJo commented
> Q. 만약 의존성이나 기타 사유 때문에 파일 체인지가 비대해지는 경우라면 PR 생성 시 별도로 원인을 남기는게 좋을까요?
>
> 네. 보통 그런 경우는 의존성 수정 작업만 단일 이슈로 처리하고 review 없음 같은 형태로 처리하는 편이 좋습니다. 코드리뷰 때에는 최대한 로직의 문맥에만 집중하기 위함이에요. 참고로 회사마다 정책 차이는 있습니다만, File change +와 - 의 합이 400 - 1000 정도여야 하는 곳도 있다고 하네요. 저희회사는 File change 15 / Line change 숫자의 합은 600 이 넘지 않도록 하는 편입니다.

> Spring Boot에서 제공하는 슬라이스 테스트처럼 테스트별 검증 범위를 (L,M,S으로) 분리 및 그룹핑하여 개발 생산성을 향상시키려는 의도로 이해하고 있습니다.
>
> 네 맞습니다. 테스트 규모를 나누는 기준 또한 조직마다 다를텐데요, 저는 이 글을 보고 분류법을 비슷하게 따라했습니다. Unit, Integration, E2E 보다 Small, Medium, Large 가 좀더 직관적인 표현이더라고요.
>
> https://testing.googleblog.com/2010/12/test-sizes.html
>
> 참고로 2010년 글이라 분류의 세부 조건은 요즘 상황과는 조금 안 맞을 수도 있습니다 ^^

2022-10-17 00:25 UTC, FrancescoJo commented on app-infrastructure/src/test/kotlin/testcase/medium/jdbc/user/UserEntityDaoTest.kt
> +        @DisplayName("loginId")
아 그렇네요. 제가 못 봤어요.

2022-10-17 00:25 UTC, FrancescoJo commented on app-infrastructure/src/test/kotlin/testcase/small/UserRepositoryImplSpec.kt
> +        @DisplayName("exact loginId")
nested test 니까 제 코멘트 무시해 주세요

2022-10-18 10:35 UTC, FrancescoJo approved these changes
고생하셨습니다.

2022-10-18 12:49 UTC, leeho1110 commented on app-infrastructure/src/test/kotlin/testcase/medium/jdbc/user/UserEntityDaoTest.kt
> +import org.junit.jupiter.api.*
이 부분은 통과합니다. 다만 프로퍼티 추가로 인해서 `detekt.yml` 132Line에 설정해둔 `constructorThreshold: 7` 때문에 app-infrastructure` 패키지에서 fail이 발생하네요. 

---

Q. detekt 통과를 위해 프로퍼티 중 일부를 별도의 클래스로 추출하거나, 설정 자체를 임계값이 맞게 변경하는 방법, 2가지가 있을 것 같은데요. 현재 별도의 클래스로 분리할만한 클래스로 느껴지는 부분을 찾기 어려워서요. 다만 임계값을 늘리는 건 단순히 눈가리고 아웅인 것 같아서 고민이 조금 되네요.

2022-10-19 12:59 UTC, abcshc approved these changes

2022-10-20 13:41 UTC, merged